- audio manager    : pavucontrol                                        
- file manager     : ranger                                             
- file manager GUI: thunar
- qemu kvm         : virt-manager                                       
- text editor      : vi                                                 
- USB mount        : udiskie > udisks2                                  
- show system info : neofetch                                           
- show wifi        : nmcli dev wifi                                     
- connect wifi     : nmcli device wifi connect "name" password "passwd" 
- bright           : brightnessctl set X0%                              
- sync config      : sync_config                                        
- org editor : emacs -nw
- system snapshots: timeshift
- media player: vlc
