- neovim : A highly extensible and configurable text editor, used for programming and editing text files.
- emacs : A powerful, extensible, customizable text editor with a wide range of features.
- pavucontrol : PulseAudio volume control tool to manage audio sources, sinks, and devices.
- ranger : A terminal-based file manager that provides a visual interface for navigating directories and files.
- thunar : A lightweight and user-friendly file manager for the XFCE desktop environment.
- udiskie : A graphical utility for automatically mounting and managing removable media.
- network-manager : A tool for managing network connections, supporting wired, wireless, VPN, and other types.
- brightnessctl : A command-line tool to adjust the screen brightness on Linux-based systems.
- i3blocks : A highly configurable status bar for the i3 window manager.
- firefox-esr : A version of the Firefox web browser intended for enterprise environments with extended support.
- chromium : An open-source web browser from which Google Chrome is derived.
- flatpak : A system for building, distributing, and running sandboxed desktop applications.
- qemu : A generic and open-source machine emulator and virtualizer, supporting KVM for hardware acceleration.
- virt-manager : A GUI tool for managing virtual machines via libvirt.
- vlc : A highly popular and versatile media player supporting many audio and video formats.
- variety : A wallpaper manager for Linux, with features such as randomizing wallpapers and managing collections.
- fcitx5 : A popular input method framework for Linux, supporting various languages, including Chinese.
- fcitx5-pinyin : A Chinese input method for typing Chinese characters using Pinyin.
- thunderbird : A free, open-source email client with support for multiple accounts and advanced features.
- timeshift : A tool for creating and managing system snapshots, useful for backup and recovery.
- steam : A digital distribution platform for video games, providing access to a large library of games.
